spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: lxp
        password: test123
        driverClassName : com.mysql.jdbc.Driver  

server:
    port: 80
    servlet:
        contextPath: /ymm
    mvc:
        view:
            prefix: /
            suffix: .html

